# Generated by Django 4.2.3 on 2023-07-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image_url', models.CharField(blank=True, max_length=2083)),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
